---
- name: preinstaall python for ansible
  hosts: db
  gather_facts: false
  tags: deploy-tag
  become: true 
  pre_tasks:
    - name: Install pythn fo Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false
