#!/bin/bash

### BEGIN INIT INFO
# Provides:          scriptname
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO
export PROGRAM_HOME=/root/reddit
program_pid() {
    echo $(ps aux | grep puma | grep -v grep | tr -s " "|cut -d" " -f2)
}
start() {
    pid=$(program_pid)
        echo -e "\e[00;32mStarting Program\e[00m"
        cd ${PROGRAM_HOME}
        puma -d
        status
}
case $1 in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        stop
        start
    ;;
    status)
        status
        exit $?
    ;;
    *)
esac
exit 0
