---
# tasks file for app Add file for puma
- name: Show info about the env this host belongs to
  debug:
          msg: "This hist is in {{ env }} environment!!!"

- include: ruby.yml
- include: puma.yml
