# Deploy APP
- name: Cheking state | check state file
  stat: path="{{ temp_folder }}/deploy1.sh"
  register: stat_result
          
- name: Remove script | if he don't work
  file:
          path: "{{ temp_folder }}/deploy1.sh"
          state: absent
  when: stat_result.stat.exists == True

- name: Clone repository | Github script
  git:
          repo: 'https://github.com/Nonamed123/sc.git'
          dest: "{{ temp_folder }}/deploy1.sh"


- name: Puma | Set execution permissionto script
  file:
          path: "{{ temp_folder }}/deploy1.sh/deploy1.sh"
          mode: "u+x"

- name: Bundler | install
  shell: "{{ temp_folder }}/deploy1.sh/deploy1.sh"

- name: Puma | Remove instalation script
  file:
          path: "{{ temp_folder }}/deploy1.sh"
          state: absent
- name : Clone repository | Github service
  git:
          repo: 'https://github.com/Nonamed123/ser.git'
          dest: "{{ temp_folder }}/puma1.service"

- name: State | File
  stat: path=/tmp/puma1.service/puma1.service
  register: stat_result

- name: Copy file | repository
  command:
          mv /tmp/puma1.service/puma1.service  /lib/systemd/system/puma.service
  when: stat_result.stat.exists == True

- name: Puma | Remove service file
  file:
          path: "{{ temp_folder }}/puma1.service"
          state: absent 

- name: Puma | State start
  service:
          name: puma
          state: started
- name: Puma | State enabled
  service:
          name: puma
          enabled: yes
