# Install MongoDB
- name: MongoDb | Import publick key
  sudo: yes
  apt_key: >
          keyserver=hkp://keyserver.ubuntu.com:80
          id=EA312927

- name: Checking status | check status file
  stat: path=/etc/apt/sources.list.d/mongodb-org-3.2.list
  register: stat_result

- name: MongoDB |Add file
  file:
          path=/etc/apt/sources.list.d/mongodb-org-3.2.list
          state=touch
  when: stat_result.stat.exists == False      

- name: MongoDB | Add repository
  sudo: yes
  lineinfile: >
          line="deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"
          dest=/etc/apt/sources.list.d/mongodb-org-3.2.list

- name: MongoDb | Install MongoDB
  apt:
          name: mongodb-org
          allow_unauthenticated: yes
          state: present
          update_cache: yes
- name: MongoDB | Ensure MongoDB is running
  service:
          name: mongod
          state: started
