---
- name: Start App
  hosts: app
  become: true
  vars:
          mongo_bind_ip: 0.0.0.0
          db_host: 10.132.15.222
  tasks:
          - name: Add unit file for puma
            become: true
            template:
                    src: /root/files/puma.service
                    dest: /etc/systemd/system/puma.service
            tags: app-tag
            notify: reload puma

          - name: Add config for DB connection
            template:
                    src: /root/templates/db_config.j2
                    dest: /root/db_config
            tags: app-tag

          - name: enable puma
            become: true
            systemd: name=puma enabled=yes
            tags: app-tag
  
  handlers:
         - name: reload puma
           become: true
           systemd: name=puma state=reloaded

