---
- name: MongoDb | Configure host
  hosts: db
  become: true
  vars:
          mongo_bind_ip: 0.0.0.0
  tasks:
          - name: Configure hosts | Change mongo config file
            become: true
            template:
                    src: /root/templates/mongod.conf.j2
                    dest: /etc/mongod.conf
                    mode: 0644
            tags: db-tag
            notify: restart mongod
  handlers:
          - name: restart mongod
            become: true
            service: name=mongod state=restarted


