---
- name: Deloy app
  hosts: app
  become: true
  tags: deploy-tag
  tasks:
          - name: Puma | Checkinng file
            stat:
                    path: /root/reddit
            register: stat_result

          - name: Fetch the latest version of application code
            git:
                    repo: 'https://github.com/Artemmkin/reddit.git'
                    dest: /root/reddit
                    version: monolith            
            when: stat_result.stat.exists == True
            notify: restart puma

          - name: Bundle install
            bundler:
                    state: present
                    chdir: /root/reddit

  handlers:
         - name: restart puma
           become: true
           systemd: name=puma state=restarted
