#Install mongo
- name : "Install MongoDB"
  hosts: all
  user: root
  tasks:
          - name: MongoDb | Import public key
            sudo: yes
            apt_key: >
                    keyserver=hkp://keyserver.ubuntu.com:80
                    id=EA312927
          - name: MongoDB | Add file
            file:
                    path=/etc/apt/sources.list.d/mongodb.list
                    state=touch
               
          - name: MongoDB | Add repository
            sudo: yes
            lineinfile: >
                    line="deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse"
                    dest=/etc/apt/sources.list.d/mongodb.list
                    state=present
          
          - name: MongoDB | Install MongoDB
            apt: 
              name: mongodb-org
              allow_unauthenticated: yes
              state: present
              update_cache: yes

          - name: MongoDB | Ensure MongoDB is running
            service: 
              name: mongod
              state: started
