---
- name: MongoDb | Configure host
  hosts: db
  become: true
  tags: db-tag
  vars:
          mongo_bind_ip: 0.0.0.0
  tasks:
          - name: MongoDB | Checking status file
            stat:
                    path: /etc/mongod.conf
            register: stat_result

          - name: Configure hosts | Change mongo config file
            become: true
            template:
                    src: /root/templates/mongod.conf.j2
                    dest: /etc/mongod.conf
                    mode: 0644
            when: stat_result.stat.exists == True
            notify: restart mongod

  handlers:
          - name: restart mongod
            become: true
            service: name=mongod state=restarted


